const fs = require('fs'), path = require('path');
const dir = path.join(__dirname, 'data', 'topics');
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

const P = (a, b) => { let r = []; a.forEach(x => b.forEach(y => r.push(x + ' ' + y))); return r; };
const U = a => [...new Set(a)];

// Gốc từ tiếng Việt để sinh cụm từ
const adj = 'đỏ,xanh,vàng,trắng,đen,nâu,tím,hồng,cam,xám,bạc,lớn,nhỏ,to,bé,cao,thấp,dài,ngắn,rộng,hẹp,dày,mỏng,nặng,nhẹ,nóng,lạnh,ấm,mát,tươi,héo,chín,sống,ngọt,chua,mặn,cay,đắng,thơm,hôi,sạch,bẩn,mới,cũ,đẹp,xấu,tốt,tệ,nhanh,chậm,mạnh,yếu,khỏe,ốm,già,trẻ,non,sáng,tối,nhạt,đậm,chói,cứng,mềm,nhẵn,sần sùi,thô,mịn,bóng,mờ,giòn,dai,rắn,lỏng,đặc,loãng,nhiều,ít,đông,vắng,ồn ào,yên tĩnh,vui,buồn,chán,thú vị,khó,dễ,phức tạp,đơn giản,đắt,rẻ,giàu,nghèo,thông minh,ngu ngốc,chăm chỉ,lười biếng,hiền,dữ,ngoan,hư,cẩn thận,cẩu thả,nhút nhát,dũng cảm,thật thà,dối trá'.split(',');

const food_roots = 'bánh,cơm,mì,phở,bún,thịt,cá,tôm,cua,mực,ốc,rau,cà,khoai,đậu,dưa,cam,xoài,chuối,nho,táo,lê,ổi,mít,bưởi,dứa,trà,sữa,nước,chè,kem,cháo,xôi,chả,gỏi,lẩu,canh,súp,gà,vịt,heo,bò,dê,ngan,ngỗng,trứng,bắp,măng,nấm,muối,đường,giấm,tiêu,ớt,hành,tỏi,gừng,sả,nghệ,quế,mè,lạc,vừng,bơ,mứt,kẹo,thạch,sữa chua,sinh tố,rau trộn,nem,giò,xúc xích,lạp xưởng,ruốc,pate,nước mắm,tương,tương ớt,tương cà,dầu ăn,mì chính,bột ngọt,hạt nêm,nước tương,xì dầu,rượu,bia,nước ngọt,nước khoáng,nước ép,bò khô,mực khô,tôm khô,cá khô,thịt nai,thịt trâu,thịt ếch,thịt lươn,thịt rắn,thịt rùa,ba ba,hải sâm,bào ngư,vi cá,tổ yến,nhân sâm,linh chi'.split(',');
const food_mod = 'chiên,nướng,hấp,luộc,xào,kho,rim,rang,quay,om,tần,ninh,bung,trộn,cuốn,nhồi,muối,ngâm,sấy,hun khói,tái,chín,sống,non,già,đông lạnh,tươi sống,khô,ướt,mặn,ngọt,chua,cay,béo,gầy,thái lát,băm nhỏ,xay nhuyễn,giã nát,vắt,ép,lọc,nấu,chưng,pha,rắn,lỏng,đặc,loãng,nóng,lạnh,đá,đường,sữa,chanh,tắc,quất,hạt é,trân châu,thạch,phô mai,bơ,tỏi,hành,tiêu,sả,ớt,sa tế,mắm tôm,mắm ruốc,mắm nêm,ngũ vị hương,lá chanh,lá lốt,tía tô,kinh giới,rau răm,thì là,hành lá,ngò rí,ngò gai,diếp cá,húng quế,húng lủi,bạc hà'.split(',');

const animal_pre = 'con,chim,cá,bò,gà,vịt,rắn,ong,kiến,bọ,sâu,nhện,chuột,sóc,thỏ,mèo,chó,hổ,báo,gấu,khỉ,voi,ngựa,dê,cừu,lợn,trâu,nai,hươu,sư tử,đại bàng,thiên nga,công,hạc,sếu,cò,diệc,vạc,le le,bồ câu,sẻ,sáo,yến,tu hú,cuốc,gõ kiến,chào mào,vành khuyên,họa mi,sơn ca,đà điểu,chim cút,chim trĩ,chim én,chim kền kền,chim cắt,chim ưng,chim ruồi,chim gáy,chim ri,chim khách,chim cú,rùa,ba ba,thằn lằn,tắc kè,kỳ nhông,kỳ đà,cá sấu,trăn,giun,đỉa,vắt,cuốn chiếu,rết,bọ cạp,tôm,cua,mực,bạch tuộc,sứa,sao biển,nhím biển,ốc biển,ngao,sò,hến,chai,hàu,vẹm,cá voi,cá heo,hải cẩu,hải mã,sư tử biển,rái cá,chồn,cáo,sói,heo rừng,nhím,tê tê,lửng,bò tót,sao la,voọc,vượn,đười ươi,tinh tinh'.split(',');
const animal_mod = 'đực,cái,con,mẹ,bố,rừng,nhà,hoang,nuôi,trắng,đen,vàng,nâu,xám,đốm,vằn,sọc,lớn,nhỏ,bé,khổng lồ,tí hon,già,non,dữ,hiền,nhanh,chậm,khỏe,đẹp,quý hiếm,biển,sông,hồ,đồng,núi,sa mạc,nhiệt đới,bắc cực,nam cực,châu á,châu âu,châu phi,châu mỹ,châu úc,ăn cỏ,ăn thịt,ăn tạp,có vú,đẻ trứng,có cánh,không cánh,có vảy,có lông,không lông,có sừng,không sừng,đuôi dài,đuôi ngắn,tai to,tai nhỏ,mắt lồi,mũi hếch,chân dài,chân ngắn,nhiều chân,ít chân,có nọc độc,không độc,biết bay,biết bơi,biết lặn,chạy nhanh,leo cây'.split(',');

const sport_roots = 'bóng đá,bóng rổ,bóng chuyền,bóng bàn,cầu lông,bơi lội,chạy bộ,nhảy cao,nhảy xa,đua xe,võ thuật,thể dục,cử tạ,bắn cung,leo núi,trượt tuyết,lướt sóng,đấu kiếm,đấu vật,cờ vua,bi da,đạp xe,tập luyện,đánh gôn,quần vợt,bắn súng,nhảy dù,trượt băng,cầu mây,đá cầu,kéo co,nhảy dây,ném đĩa,đẩy tạ,chạy vượt rào,bơi bướm,bơi ếch,bơi ngửa,bơi sải,chạy đường dài,ba môn phối hợp,bóng ném,bóng nước,khúc côn cầu,bóng bầu dục,điền kinh,bóng đá trong nhà,cờ tướng,cờ vây,cờ cá ngựa,cờ tỷ phú,cờ vua,lắc vòng,nhảy múa,khiêu vũ,thể hình,vật tay,nhảy cầu,thể dục dụng cụ,nhào lộn,đu xà,trượt ván,trượt patin,đua thuyền,chèo thuyền,đua ngựa,đua chó,cưỡi ngựa,bay lượn,nhảy bungee,lặn biển,leo vách đá,đi bộ,đi bộ nhanh,marathon,đua xe đạp,đua mô tô,đua ô tô,bóng chày,bóng mềm,cầu lông,tennis,cầu mây,bóng chuyền bãi biển'.split(',');
const sport_mod = 'chuyên nghiệp,nghiệp dư,quốc tế,quốc gia,trẻ,nữ,nam,đồng đội,cá nhân,đôi,trong nhà,ngoài trời,bãi biển,mùa đông,mùa hè,dưới nước,trên băng,tốc độ,sức bền,chiến thuật,kỹ thuật,phòng thủ,tấn công,mạnh,nhanh,chậm,kéo dài,ngắn hạn,bền bỉ,khéo léo,mạo hiểm,an toàn,giải trí,thi đấu,giao hữu,thể thao,vận động,rèn luyện,khỏe mạnh,năng động,tập thể,cá nhân,đơn nam,đơn nữ,đôi nam,đôi nữ,đôi nam nữ,phong trào,thành tích cao,nghệ thuật,đỉnh cao,châu á,châu âu,thế giới,toàn quốc,địa phương,trường học,thanh niên,thiếu niên,nhi đồng,người cao tuổi,người khuyết tật'.split(',');

const color_roots = 'đỏ,xanh,vàng,trắng,đen,hồng,tím,cam,nâu,xám,bạc,kem,be,lục,chàm,lam,tía,huyết,bã trầu,cánh sen,lòng tôm,đọt chuối,rêu,da trời,nước biển,ngọc bích,lục bảo,lông chuột,tro,chì,đồng,chì,thiếc,gạch,đất,cát,gỗ,sữa,ngà,tinh,muốt,phấn,son,rượu vang,nho,đào,chanh,chuối,cam,quýt,bưởi,dưa hấu,cà chua,ớt,cà rốt,bí ngô,khoai môn,hoa mười giờ,hoa cúc,hoa mai,hoa đào,hoa hồng,hoa lan,hoa sen,hoa súng,hoa phượng,hoa phượng tím,hoa bằng lăng,hoa bỉ ngạn'.split(',');
const color_mod = 'đậm,nhạt,tươi,sáng,tối,thẫm,rực,nhạt màu,chói,ánh kim,kim loại,phát sáng,mờ,trong,đục,óng,lỳ,bóng,nhám,ngọc,than,cháy,khói,bụi,bạc màu,phai màu,cũ,mới,đẹp,xấu,lạ,quen,độc đáo,phổ biến,tự nhiên,nhân tạo,nhuộm,tẩy,sơn,vẽ,in,phun,phối,pha,trộn,hòa quyện,đơn sắc,đa sắc,nhiều màu,rực rỡ,sặc sỡ,lòe loẹt,nhã nhặn,thanh lịch,sang trọng,cổ điển,hiện đại,truyền thống,phá cách,trầm,ấm,lạnh,mát,dịu,gắt,chói lóa,chói chang,mờ ảo,mờ nhạt,rõ nét,sắc nét'.split(',');
const color_things = 'áo,quần,váy,giày,túi,mũ,khăn,tóc,mắt,môi,má,da,hoa,lá,trời,biển,mây,nắng,hoàng hôn,bình minh,sơn,vải,gạch,ngói,đá,gỗ,xe,tường,cửa,rèm,thảm,gối,chăn,ga,nến,đèn,bút,sách,tranh,son,phấn,ô,dù,kính,nhẫn,vòng,dây chuyền,bông tai,nhà,sân,vườn,cổng,hàng rào,bàn,ghế,tủ,giường,kệ,bếp,nồi,chảo,bát,đĩa,cốc,ly,chai,lọ,bình,chậu,xô,thau,giỏ,làn,túi xách,ba lô,cặp,ví,nịt,thắt lưng,găng tay,tất,vớ,khẩu trang,mũ bảo hiểm,xe đạp,xe máy,ô tô,xe tải,máy bay,tàu hỏa,thuyền,bè'.split(',');

const place_vn = 'hà nội,sài gòn,đà nẵng,huế,hải phòng,cần thơ,nha trang,đà lạt,vũng tàu,quy nhơn,phú quốc,hội an,sa pa,hạ long,ninh bình,tam đảo,mũi né,phan thiết,buôn ma thuột,pleiku,bắc ninh,bắc giang,thái nguyên,lạng sơn,hà giang,lào cai,yên bái,sơn la,điện biên,lai châu,hòa bình,phú thọ,tuyên quang,cao bằng,hà nam,nam định,thái bình,thanh hóa,nghệ an,hà tĩnh,quảng bình,quảng trị,quảng nam,quảng ngãi,bình định,phú yên,khánh hòa,bình thuận,kon tum,gia lai,đắk lắk,đắk nông,lâm đồng,bình phước,tây ninh,bà rịa,trà vinh,vĩnh long,đồng tháp,sóc trăng,bạc liêu,cà mau,hậu giang,bình dương,đồng nai,long an,bến tre,tiền giang,an giang,kiên giang,hưng yên,hải dương,vĩnh phúc,bắc kạn,thừa thiên huế,thành phố hồ chí minh'.split(',');
const place_features = 'vịnh,đảo,sông,hồ,núi,đèo,thác,bãi biển,cầu,chùa,đền,miếu,lăng,phố cổ,hang động,suối,đầm,vườn quốc gia,khu bảo tồn,di tích,thành cổ,cung điện,bảo tàng,nhà thờ,tháp,quảng trường,chợ,bến cảng,sân bay,ga tàu,bến xe,trạm thu phí,khu công nghiệp,khu chế xuất,khu đô thị,khu dân cư,làng,bản,ấp,xóm,thôn,phường,xã,thị trấn,quận,huyện,thành phố,tỉnh,vùng,miền,quốc gia,châu lục,hòn đảo,quần đảo,bán đảo,vùng vịnh,eo biển,rạn san hô,rừng,rừng nguyên sinh,rừng rậm,rừng ngập mặn,rừng thông,rừng phòng hộ,sa mạc,bán sa mạc,thảo nguyên,cao nguyên,đồng bằng,châu thổ,vùng ven biển,vùng núi,vùng cao,biên giới,cửa khẩu'.split(',');

const job_roots = 'bác sĩ,giáo viên,kỹ sư,luật sư,công an,cảnh sát,quân nhân,ca sĩ,diễn viên,đạo diễn,họa sĩ,nhạc sĩ,nhà văn,nhà thơ,nhà báo,phóng viên,kiến trúc sư,dược sĩ,nha sĩ,y tá,điều dưỡng,giám đốc,kế toán,thư ký,phi công,tiếp viên,đầu bếp,tài xế,thợ điện,thợ mộc,thợ may,thợ hàn,thợ sơn,thợ xây,nông dân,ngư dân,lập trình viên,nhiếp ảnh gia,nhà khoa học,vũ công,người mẫu,trọng tài,huấn luyện viên,biên tập viên,phát thanh viên,thẩm phán,kiểm sát viên,công chứng viên,thám tử,bảo vệ,lính cứu hỏa,cứu hộ,hộ sinh,hộ lý,giảng viên,giáo sư,nghiên cứu sinh,thạc sĩ,tiến sĩ,quản lý,doanh nhân,nhà đầu tư,môi giới,phục vụ,thợ cắt tóc,thợ sửa xe,nhà thiết kế,nghệ sĩ,biên kịch,nhà soạn nhạc,thợ kim hoàn,thú y,chuyên gia,tư vấn viên,hướng dẫn viên,phiên dịch,biên dịch,nhà ảo thuật,nhạc trưởng,nhà điêu khắc,thợ gốm,thợ rèn,thợ lặn,thợ mỏ,thợ giầy,thợ khóa,thợ sửa ống nước,thợ làm bánh,thợ pha chế,nhân viên thu ngân,nhân viên kho,nhân viên dọn dẹp,nhân viên bảo vệ,nhân viên an ninh,nhân viên cứu hộ,nhân viên lễ tân,nhân viên hành chính,nhân viên kinh doanh,nhân viên tiếp thị,nhân viên chăm sóc khách hàng'.split(',');
const job_mod = 'trưởng,phó,chính,phụ,tập sự,thực tập,chuyên nghiệp,nghiệp dư,giỏi,tài năng,nổi tiếng,trẻ,già,kỳ cựu,mới vào nghề,tự do,toàn thời gian,bán thời gian,trực tuyến,về hưu,xuất sắc,tệ,thiếu kinh nghiệm,giàu kinh nghiệm,cấp cao,cấp thấp,cấp trung,trưởng nhóm,nhóm trưởng,quản lý,trợ lý,thư ký,đại diện,ủy quyền,độc lập,hợp đồng,biên chế,thời vụ,công nhật,khoán,chuyên gia,cố vấn,giám sát,thanh tra,kiểm tra,đánh giá,phân tích,thiết kế,triển khai,vận hành,bảo trì,sửa chữa,cài đặt,lắp ráp,gia công,sản xuất,chế tạo,sáng chế,phát minh,nghiên cứu,giảng dạy,đào tạo,huấn luyện'.split(',');

const items_roots = 'bàn,ghế,tủ,giường,cửa,đèn,quạt,tivi,máy lạnh,tủ lạnh,máy giặt,bếp,nồi,chảo,bát,đũa,thìa,dĩa,dao,thớt,rổ,rá,thau,chậu,bình,ly,cốc,chén,gương,lược,khăn,chiếu,chăn,màn,gối,sách,vở,bút,thước,tẩy,kéo,keo,túi,ví,cặp,balo,nón,mũ,áo,quần,váy,đầm,tất,vớ,giày,dép,ủng,đồng hồ,điện thoại,máy tính,bàn phím,chuột,loa,tai nghe,micro,pin,sạc,dây,cáp,ổ cắm,công tắc,phích cắm,kìm,búa,cờ lê,mỏ lết,tua vít,đinh,ốc,vít,cưa,khoan,thước cuộn,chổi,hót rác,lau nhà,thùng rác,bao rác,móc,kẹp,chậu hoa,bình hoa,tranh,ảnh,khung,lịch,đồng hồ treo tường,đèn pin,đèn bàn,đèn trần,quạt trần,quạt bàn,quạt cây,quạt treo tường,bếp ga,bếp từ,bếp điện,lò vi sóng,lò nướng,máy xay,máy ép,máy hút bụi,máy sấy,bàn ủi,cầu là,máy sưởi,máy lọc nước,máy hút mùi'.split(',');
const items_mod = 'gỗ,sắt,nhựa,inox,thủy tinh,sứ,da,vải,len,giấy,điện,thông minh,cũ,mới,to,nhỏ,dài,ngắn,cao,thấp,dày,mỏng,nặng,nhẹ,đỏ,xanh,vàng,trắng,đen,đắt,rẻ,bền,hỏng,gãy,rách,đẹp,xấu,tốt,tệ,hiện đại,cổ điển,truyền thống,thủ công,công nghiệp,tự động,bán tự động,cầm tay,để bàn,treo tường,âm tường,di động,cố định,gấp gọn,xếp,đa năng,chuyên dụng,đơn giản,phức tạp,an toàn,nguy hiểm,độc hại,thân thiện,bảo vệ,trang trí,thực dụng,cá nhân,gia đình,công cộng,văn phòng,trường học,bệnh viện,nhà máy,công xưởng,ngoài trời,trong nhà,chống nước,chống cháy,chống ồn,chống sốc,cách điện,cách nhiệt'.split(',');

const plants_roots = 'cây,hoa,lá,cành,rễ,quả,trái,mầm,nụ,chồi,hạt,củ,thân,gỗ,tre,trúc,nứa,mai,đào,lan,cúc,sen,súng,hồng,huệ,nhài,ly,đồng tiền,hướng dương,phong lan,mười giờ,cẩm tú cầu,phượng,bàng,đa,đề,si,gạo,xoan,thông,tùng,bách,dương,liễu,phi lao,bạch đàn,keo,cao su,cà phê,hồ tiêu,điều,bưởi,cam,chanh,quýt,xoài,nhãn,vải,chôm chôm,sầu riêng,mít,ổi,mận,mơ,lê,táo,chuối,đu đủ,dưa hấu,dưa chuột,bí ngô,bí đao,mướp,bầu,cà chua,cà tím,ớt,tiêu,hành,tỏi,gừng,sả,rau,cỏ,rêu,nấm,tảo,dương xỉ,bèo,rong,lúa,ngô,khoai,sắn,đậu,lạc,vừng,mía,bông,dâu,tằm,chè,thuốc lá,thuốc lào,trầu,cau,dừa,cọ,chuối tiêu,chuối hột,chuối tây,chuối sáp,đu đủ xanh,đu đủ chín,chanh dây,chanh muối,chanh đào,cam sành,cam vinh,cam canh,bưởi diễn,bưởi năm roi,bưởi da xanh,nhãn lồng,vải thiều,chôm chôm nhãn,sầu riêng hạt lép,mít tố nữ,mít thái,ổi bo,mận hà nội,đào sapa,lê mắc cọp,táo mèo,táo ta,táo tây'.split(',');
const plants_mod = 'to,nhỏ,cao,thấp,lớn,bé,non,già,tươi,héo,khô,rụng,xanh,vàng,đỏ,tím,trắng,hồng,thơm,đẹp,quý,hiếm,dại,rừng,nhà,cảnh,ăn quả,lấy gỗ,bóng mát,thân thảo,thân gỗ,dây leo,thủy sinh,phù du,nhiệt đới,ôn đới,hàn đới,sa mạc,núi cao,đồng bằng,ven biển,ngập mặn,nước ngọt,nước mặn,nước lợ,có gai,không gai,có độc,không độc,chữa bệnh,làm thuốc,làm cảnh,làm thức ăn,làm gia vị,làm đồ uống,công nghiệp,nông nghiệp,lâm nghiệp,thủy sản,trồng,mọc hoang,nhân giống,lai tạo,đột biến,cổ thụ,cổ đại,hóa thạch'.split(',');

const natural_roots = 'gió,mưa,nắng,mây,trời,đất,nước,lửa,sét,sấm,chớp,bão,lũ,lụt,hạn hán,động đất,sóng thần,núi lửa,tuyết,băng,sương,mù,sương muối,cầu vồng,bình minh,hoàng hôn,nhật thực,nguyệt thực,sao,trăng,mặt trời,trái đất,vũ trụ,thiên hà,hành tinh,tiểu hành tinh,sao chổi,sao băng,thiên thạch,không gian,thời gian,ngày,đêm,sáng,trưa,chiều,tối,khuya,mùa xuân,mùa hạ,mùa thu,mùa đông,tháng,năm,thế kỷ,thiên niên kỷ,thập kỷ,khoảnh khắc,giây,phút,giờ,khí hậu,thời tiết,nhiệt độ,độ ẩm,áp suất,gió mùa,gió tây,gió đông,gió nam,gió bắc,bão nhiệt đới,áp thấp,lốc xoáy,vòi rồng,mưa rào,mưa phùn,mưa đá,mưa bóng mây,nắng gắt,nắng nhẹ,trời trong,trời râm,trời tối,sương mù dày,sương mai,hừng đông,chiều tà,đêm khuya,nửa đêm,rạng sáng,tờ mờ sáng,chạng vạng,hoàng hôn buông'.split(',');
const natural_mod = 'to,nhỏ,lớn,bé,nhiều,ít,mạnh,yếu,nóng,lạnh,ấm,mát,khô,ẩm,đẹp,xấu,dữ dội,êm đềm,nhẹ nhàng,khủng khiếp,nguy hiểm,an toàn,bất ngờ,dự báo,kéo dài,ngắn,nhanh,chậm,đột ngột,từ từ,rực rỡ,âm u,u ám,trong xanh,quang đãng,mịt mờ,dày đặc,loãng,rải rác,cục bộ,diện rộng,toàn cầu,địa phương,khu vực,quốc tế,xuyên quốc gia,lịch sử,kỷ lục,hiếm thấy,thường xuyên,liên tục,gián đoạn,định kỳ,bất thường,khắc nghiệt,ôn hòa,thuận lợi,bất lợi,thiên nhiên,tự nhiên,nhân tạo,hữu hình,vô hình'.split(',');

function gen(name, fn) {
  const words = U(fn());
  const file = path.join(dir, name + '.json');
  fs.writeFileSync(file, JSON.stringify(words, null, 0), 'utf8');
  console.log(`${name}: ${words.length} từ`);
  return words.length;
}

let total = 0;
total += gen('thuc_pham', () => [...P(food_roots, food_mod), ...P(food_roots, adj.slice(0, 30))]);
total += gen('dong_vat', () => [...P(animal_pre, animal_mod), ...P(['con'], animal_pre), ...P(animal_pre, adj.slice(0, 30))]);
total += gen('the_thao', () => [...P(sport_roots, sport_mod), ...P(sport_roots, adj.slice(0, 20))]);
total += gen('mau_sac', () => [...P(color_roots, color_mod), ...P(color_things, color_roots), ...P(['màu'], color_roots)]);
total += gen('dia_danh', () => [...place_vn, ...P(place_features, place_vn), ...P(place_features, adj.slice(0, 30))]);
total += gen('nghe_nghiep', () => [...P(job_roots, job_mod), ...job_roots, ...P(job_roots, adj.slice(0, 30))]);
total += gen('do_vat', () => [...P(items_roots, items_mod), ...P(items_roots, adj.slice(0, 40))]);
total += gen('thuc_vat', () => [...P(plants_roots, plants_mod), ...P(plants_roots, adj.slice(0, 40))]);
total += gen('thien_nhien', () => [...P(natural_roots, natural_mod), ...P(natural_roots, adj.slice(0, 40))]);

console.log(`\n✅ Tổng cộng: ${total} từ đã được sinh!`);
